/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ProofOfExistenceInterface extends Interface {
  getFunction(nameOrSignature: "getProof" | "notarize"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Notarized"): EventFragment;

  encodeFunctionData(functionFragment: "getProof", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "notarize", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "getProof", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "notarize", data: BytesLike): Result;
}

export namespace NotarizedEvent {
  export type InputTuple = [
    documentHash: BytesLike,
    owner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    documentHash: string,
    owner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    documentHash: string;
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProofOfExistence extends BaseContract {
  connect(runner?: ContractRunner | null): ProofOfExistence;
  waitForDeployment(): Promise<this>;

  interface: ProofOfExistenceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getProof: TypedContractMethod<
    [documentHash: BytesLike],
    [[bigint, string]],
    "view"
  >;

  notarize: TypedContractMethod<
    [documentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getProof"
  ): TypedContractMethod<[documentHash: BytesLike], [[bigint, string]], "view">;
  getFunction(
    nameOrSignature: "notarize"
  ): TypedContractMethod<[documentHash: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "Notarized"
  ): TypedContractEvent<
    NotarizedEvent.InputTuple,
    NotarizedEvent.OutputTuple,
    NotarizedEvent.OutputObject
  >;

  filters: {
    "Notarized(bytes32,address,uint256)": TypedContractEvent<
      NotarizedEvent.InputTuple,
      NotarizedEvent.OutputTuple,
      NotarizedEvent.OutputObject
    >;
    Notarized: TypedContractEvent<
      NotarizedEvent.InputTuple,
      NotarizedEvent.OutputTuple,
      NotarizedEvent.OutputObject
    >;
  };
}
